# This is a basic workflow to help you get started with Actions

name: Pull from pantheon

# Controls when the workflow will run
on:
  # Triggers the workflow to run every 5 minutes
  schedule:
    - cron: "*/5 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  auto-pull:
    name: PullPantheonOrigin
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "test"
